import Navigtaion from "@/app/components/header/navgitation/Navigation"
import Search from "@/app/components/header/search/Search"
import type { Metadata } from "next"

export const metadata: Metadata = {
    title: "Choice",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>
                <Navigtaion />
                <Search />
                {children}
            </body>
        </html>
    )
}
