import type { Metadata } from "next"
import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"
import "./globals.css"
import { Provider } from "./Provider"
import Navigation from "./components/header/navgitation/Navigation"
import Search from "./components/header/search/Search"
import Footer from "./components/footer/Footer"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>
                <Provider>
                    {children}
                    <Footer />
                </Provider>
            </body>
        </html>
    )
}
